# This is a config for E2B sandbox template.
# You can use template ID (s3fnj8q3lbghad1f15u6) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("s3fnj8q3lbghad1f15u6") # Sync sandbox
# sandbox = await AsyncSandbox.create("s3fnj8q3lbghad1f15u6") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('s3fnj8q3lbghad1f15u6')

team_id = "288f5ade-729e-4e1c-b184-cfd4cb8f4779"
memory_mb = 4_096
cpu_count = 4
start_cmd = "cd /home/user && npx next --turbo"
dockerfile = "e2b.Dockerfile"
template_id = "s3fnj8q3lbghad1f15u6"
